options_producer={"'Bandai Visual'": "'Bandai Visual'",
 "'Sunrise'": "'Sunrise'",
 "'Victor Entertainment'": "'Victor Entertainment'",
 "'TV Tokyo'": "'TV Tokyo'",
 "'Nihon Ad Systems'": "'Nihon Ad Systems'",
 "'TV Tokyo Music'": "'TV Tokyo Music'",
 "'Shueisha'": "'Shueisha'",
 "'Genco'": "'Genco'",
 "'Fuji TV'": "'Fuji TV'",
 "'OB Planning'": "'OB Planning'",
 "'Studio Jack'": "'Studio Jack'",
 "'VAP'": "'VAP'",
 "'Shogakukan Productions'": "'Shogakukan Productions'",
 "'Nippon Television Network'": "'Nippon Television Network'",
 "'Aniplex'": "'Aniplex'",
 "'Production I.G'": "'Production I.G'",
 "'Sotsu'": "'Sotsu'",
 "'Marvelous'": "'Marvelous'",
 "'Starchild Records'": "'Starchild Records'",
 "'Media Factory'": "'Media Factory'",
 "'DAX Production'": "'DAX Production'",
 "'GDH'": "'GDH'",
 "'Pony Canyon'": "'Pony Canyon'",
 "'CBC'": "'CBC'",
 "'Group TAC'": "'Group TAC'",
 "'Rondo Robe'": "'Rondo Robe'",
 "'Pioneer LDC'": "'Pioneer LDC'",
 "'d-rights'": "'d-rights'",
 "'Tohokushinsha Film Corporation'": "'Tohokushinsha Film Corporation'",
 "'Atelier Musa'": "'Atelier Musa'",
 "'TBS'": "'TBS'",
 "'Kadokawa Shoten'": "'Kadokawa Shoten'",
 "'Audio Tanaka'": "'Audio Tanaka'",
 "'Movic'": "'Movic'",
 "'Sega'": "'Sega'",
 "'Toei Animation'": "'Toei Animation'",
 "'Hakusensha'": "'Hakusensha'",
 "'Kodansha'": "'Kodansha'",
 "'SME Visual Works'": "'SME Visual Works'",
 "'Sony Music Entertainment'": "'Sony Music Entertainment'",
 "'Mainichi Broadcasting System'": "'Mainichi Broadcasting System'",
 "'Toho'": "'Toho'",
 "'Yomiko Advertising'": "'Yomiko Advertising'",
 "'Bandai'": "'Bandai'",
 "'CyberConnect2'": "'CyberConnect2'",
 "'KSS'": "'KSS'",
 "'Half H.P Studio'": "'Half H.P Studio'",
 "'Nichion'": "'Nichion'",
 "'AIC'": "'AIC'",
 "'Lantis'": "'Lantis'",
 "'Cosmic Ray'": "'Cosmic Ray'",
 "'TYO Animations'": "'TYO Animations'",
 "'TYO'": "'TYO'",
 "'Sony Pictures Entertainment'": "'Sony Pictures Entertainment'",
 "'Asatsu DK'": "'Asatsu DK'",
 "'Youmex'": "'Youmex'",
 "'Toshiba EMI'": "'Toshiba EMI'",
 "'King Records'": "'King Records'",
 "'Hal Film Maker'": "'Hal Film Maker'",
 "'Mellow Head'": "'Mellow Head'",
 "'Memory-Tech'": "'Memory-Tech'",
 "'Imagica'": "'Imagica'",
 "'Sotsu Music Publishing'": "'Sotsu Music Publishing'",
 "'Dentsu'": "'Dentsu'",
 "'Tatsunoko Production'": "'Tatsunoko Production'",
 "'Rakuonsha'": "'Rakuonsha'",
 "'Kadokawa Pictures Japan'": "'Kadokawa Pictures Japan'",
 "'KlockWorx'": "'KlockWorx'",
 "'Happinet Pictures'": "'Happinet Pictures'",
 "'Animation Do'": "'Animation Do'",
 "'Sogo Vision'": "'Sogo Vision'",
 "'Omnibus Japan'": "'Omnibus Japan'",
 "'Nagoya TV Housou'": "'Nagoya TV Housou'",
 "'Nozomi Entertainment'": "'Nozomi Entertainment'",
 "'Shochiku'": "'Shochiku'",
 "'TV Asahi'": "'TV Asahi'",
 "'Apollon'": "'Apollon'",
 "'Studio Zain'": "'Studio Zain'",
 "'Animax'": "'Animax'",
 "'Toei Video'": "'Toei Video'",
 "'Sunny Side Up'": "'Sunny Side Up'",
 "'NHK'": "'NHK'",
 "'Studio Tron'": "'Studio Tron'",
 "'m.o.e.'": "'m.o.e.'",
 "'Geneon Universal Entertainment'": "'Geneon Universal Entertainment'",
 "'SoftX'": "'SoftX'",
 "'Trinet Entertainment'": "'Trinet Entertainment'",
 "'Square Enix'": "'Square Enix'",
 "'Dream Force'": "'Dream Force'",
 "'GANSIS'": "'GANSIS'",
 "'Studio Fantasia'": "'Studio Fantasia'",
 "'Remic'": "'Remic'",
 "'Front Line'": "'Front Line'",
 "'Toshiba Entertainment'": "'Toshiba Entertainment'",
 "'Fuji Pacific Music Publishing'": "'Fuji Pacific Music Publishing'",
 "'Age'": "'Age'",
 "'Marubeni'": "'Marubeni'",
 "'Shelty'": "'Shelty'",
 "'chara-ani.com'": "'chara-ani.com'",
 "'KENMedia'": "'KENMedia'",
 "'Broccoli'": "'Broccoli'",
 "'Avex Entertainment'": "'Avex Entertainment'",
 "'Tokuma Shoten'": "'Tokuma Shoten'",
 "'A-Line'": "'A-Line'",
 "'Studio Izena'": "'Studio Izena'",
 "'MediaNet'": "'MediaNet'",
 "'Discovery'": "'Discovery'",
 "'WAO World'": "'WAO World'",
 "'Sony PCL'": "'Sony PCL'",
 "'TAP'": "'TAP'",
 "'Green Bunny'": "'Green Bunny'",
 "'Barnum Studio'": "'Barnum Studio'",
 "'flying DOG'": "'flying DOG'",
 "'Studio Deen'": "'Studio Deen'",
 "'Kitty Films'": "'Kitty Films'",
 "'Shogakukan'": "'Shogakukan'",
 "'SOEISHINSHA'": "'SOEISHINSHA'",
 "'I-move'": "'I-move'",
 "'SKY Perfect Well Think'": "'SKY Perfect Well Think'",
 "'Shounen Gahousha'": "'Shounen Gahousha'",
 "'YTV'": "'YTV'",
 "'HoriPro'": "'HoriPro'",
 "'Ashi Production'": "'Ashi Production'",
 "'Bandai Namco Games'": "'Bandai Namco Games'",
 "'Hakuhodo DY Media Partners'": "'Hakuhodo DY Media Partners'",
 "'Bandai Channel'": "'Bandai Channel'",
 "'USEN'": "'USEN'",
 "'Kids Station'": "'Kids Station'",
 "'Yomiuri Telecasting'": "'Yomiuri Telecasting'",
 "'Studio Kelmadick'": "'Studio Kelmadick'",
 "'Amber Film Works'": "'Amber Film Works'",
 "'gimik'": "'gimik'",
 "'Capcom'": "'Capcom'",
 "'Tokyo Movie Shinsha'": "'Tokyo Movie Shinsha'",
 "'RCC Chugoku Broadcasting'": "'RCC Chugoku Broadcasting'",
 "'Dentsu Tec'": "'Dentsu Tec'",
 "'TMS-Kyokuchi'": "'TMS-Kyokuchi'",
 "'Free-Will'": "'Free-Will'",
 "'Heewon Entertainment'": "'Heewon Entertainment'",
 "'WOWOW'": "'WOWOW'",
 "'BeSTACK'": "'BeSTACK'",
 "'NBCUniversal Entertainment Japan'": "'NBCUniversal Entertainment Japan'",
 "'On The Run'": "'On The Run'",
 "'Polygram Japan'": "'Polygram Japan'",
 "'Film Workshop'": "'Film Workshop'",
 "'Pink Pineapple'": "'Pink Pineapple'",
 "'Critical Mass Video'": "'Critical Mass Video'",
 "'BEAM Entertainment'": "'BEAM Entertainment'",
 "'Nippon Columbia'": "'Nippon Columbia'",
 "'Trans Arts'": "'Trans Arts'",
 "'Animate Film'": "'Animate Film'",
 "'Asahi Broadcasting'": "'Asahi Broadcasting'",
 "'Fuji Creative'": "'Fuji Creative'",
 "'Frontier Works'": "'Frontier Works'",
 "'Notes'": "'Notes'",
 "'Showgate'": "'Showgate'",
 "'Kansai Telecasting'": "'Kansai Telecasting'",
 "'Studio Tulip'": "'Studio Tulip'",
 "'Idea Factory'": "'Idea Factory'",
 "'Design Factory'": "'Design Factory'",
 "'Studio Nue'": "'Studio Nue'",
 "'G&amp;G Entertainment'": "'G&amp;G Entertainment'",
 "'81 Produce'": "'81 Produce'",
 "'Kyoto Animation'": "'Kyoto Animation'",
 "'Production Reed'": "'Production Reed'",
 "'Delfi Sound'": "'Delfi Sound'",
 "'Trilogy Future Studio'": "'Trilogy Future Studio'",
 "'Mag Garden'": "'Mag Garden'",
 "'Takeshobo'": "'Takeshobo'",
 "'AnimEigo'": "'AnimEigo'",
 "'Network'": "'Network'",
 "'Japan Home Video'": "'Japan Home Video'",
 "'Soft Garage'": "'Soft Garage'",
 "'Picture Magic'": "'Picture Magic'",
 "'Synergy Japan'": "'Synergy Japan'",
 "'J.C.Staff'": "'J.C.Staff'",
 "'Four Some'": "'Four Some'",
 "'Gakken'": "'Gakken'",
 "'Big West'": "'Big West'",
 "'Media Rings'": "'Media Rings'",
 "'TV Setouchi'": "'TV Setouchi'",
 "'Topcraft'": "'Topcraft'",
 "'San-X'": "'San-X'",
 "'Madhouse'": "'Madhouse'",
 "'Rikuentai'": "'Rikuentai'",
 "'Asmik Ace Entertainment'": "'Asmik Ace Entertainment'",
 "'Three Fat Samurai'": "'Three Fat Samurai'",
 "'Sol Blade'": "'Sol Blade'",
 "'Studio OX'": "'Studio OX'",
 "'Asahi Production'": "'Asahi Production'",
 "'TV Osaka'": "'TV Osaka'",
 "'Yomiuri Advertising'": "'Yomiuri Advertising'",
 "'Toshiba Digital Frontiers'": "'Toshiba Digital Frontiers'",
 "'Studio Take Off'": "'Studio Take Off'",
 "'AT-X'": "'AT-X'",
 "'Triangle Staff'": "'Triangle Staff'",
 "'Studio Flag'": "'Studio Flag'",
 "'Radix'": "'Radix'",
 "'TV Aichi'": "'TV Aichi'",
 "'TMS Entertainment'": "'TMS Entertainment'",
 "'On-Lead'": "'On-Lead'",
 "'Marvelous AQL'": "'Marvelous AQL'",
 "'EMI'": "'EMI'",
 "'Ajia-Do'": "'Ajia-Do'",
 "'Studio Kyuuma'": "'Studio Kyuuma'",
 "'Studio Core'": "'Studio Core'",
 "'CBS'": "'CBS'",
 "'Milky Animation Label'": "'Milky Animation Label'",
 "'Phoenix Entertainment'": "'Phoenix Entertainment'",
 "'Alchemist'": "'Alchemist'",
 "'Echo'": "'Echo'",
 "'Sakura Create'": "'Sakura Create'",
 "'Digiturbo'": "'Digiturbo'",
 "'Animaruya'": "'Animaruya'",
 "'Shaft'": "'Shaft'",
 "'SynergySP'": "'SynergySP'",
 "'Nippon Shuppan Hanbai (Nippan) K.K.'": "'Nippon Shuppan Hanbai (Nippan) K.K.'",
 "'Digital Works'": "'Digital Works'",
 "'Visual Art&#039;s'": "'Visual Art&#039;s'",
 "'Dwango'": "'Dwango'",
 "'AQUAPLUS'": "'AQUAPLUS'",
 "'Nippon Ichi Software'": "'Nippon Ichi Software'",
 "'Futabasha'": "'Futabasha'",
 "'Beyond C.'": "'Beyond C.'",
 "'Grouper Productions'": "'Grouper Productions'",
 "'Trinity Sound'": "'Trinity Sound'",
 "'Audio Highs'": "'Audio Highs'",
 "'Miracle Robo'": "'Miracle Robo'",
 "'Hasbro'": "'Hasbro'",
 "'ASCII Media Works'": "'ASCII Media Works'",
 "'Tablier Communication'": "'Tablier Communication'",
 "'Dynamic Planning'": "'Dynamic Planning'",
 "'Jade Animation'": "'Jade Animation'",
 "'Active'": "'Active'",
 "'T.P.O'": "'T.P.O'",
 "'Magic Capsule'": "'Magic Capsule'",
 "'GAGA'": "'GAGA'",
 "'Marine Entertainment'": "'Marine Entertainment'",
 "'Daiei'": "'Daiei'",
 "'CoMix Wave Films'": "'CoMix Wave Films'",
 "'NEC Avenue'": "'NEC Avenue'",
 "'Studio Comet'": "'Studio Comet'",
 "'Studio Ghibli'": "'Studio Ghibli'",
 "'Bee Media'": "'Bee Media'",
 "'Nippon Cultural Broadcasting'": "'Nippon Cultural Broadcasting'",
 "'CherryLips'": "'CherryLips'",
 "'Nelvana'": "'Nelvana'",
 "'Oz'": "'Oz'",
 "'Sanctuary'": "'Sanctuary'",
 "'E&amp;G Films'": "'E&amp;G Films'",
 "'Darts'": "'Darts'",
 "'Shuuhei Morita'": "'Shuuhei Morita'",
 "'Bushiroad'": "'Bushiroad'",
 "'Ai ga areba Daijobu'": "'Ai ga areba Daijobu'",
 "'Oh! Production'": "'Oh! Production'",
 "'Tokyu Recreation'": "'Tokyu Recreation'",
 "'Sav! The World Productions'": "'Sav! The World Productions'",
 "'Teichiku Entertainment'": "'Teichiku Entertainment'",
 "'Actas'": "'Actas'",
 "'Hero Communication'": "'Hero Communication'",
 "'Kitty Media'": "'Kitty Media'",
 "'BMG Japan'": "'BMG Japan'",
 "'Nihon Falcom'": "'Nihon Falcom'",
 "'DiC Entertainment'": "'DiC Entertainment'",
 "'Artmic'": "'Artmic'",
 "'Yamamura Animation": "'Yamamura Animation",
 "Inc.'": "Inc.'",
 "'D3'": "'D3'",
 "'Silky’s'": "'Silky’s'",
 "'Himajin Planning'": "'Himajin Planning'",
 "'Bee Train'": "'Bee Train'",
 "'Viz Media'": "'Viz Media'",
 "'Tezuka Productions'": "'Tezuka Productions'",
 "'Image Kei'": "'Image Kei'",
 "'Konami'": "'Konami'",
 "'Ginga Ya'": "'Ginga Ya'",
 "'Akita Shoten'": "'Akita Shoten'",
 "'APPP'": "'APPP'",
 "'Tokyo Kids'": "'Tokyo Kids'",
 "'Pony Canyon Enterprise'": "'Pony Canyon Enterprise'",
 "'Nintendo'": "'Nintendo'",
 "'K-Factory'": "'K-Factory'",
 "'Bandai Namco Entertainment'": "'Bandai Namco Entertainment'",
 "'Koei'": "'Koei'",
 "'Banpresto'": "'Banpresto'",
 "'Venus Vangard'": "'Venus Vangard'",
 "'BS-i'": "'BS-i'",
 "'NuTech Digital'": "'NuTech Digital'",
 "'Natural High'": "'Natural High'",
 "'AC Create'": "'AC Create'",
 "'NichiNare'": "'NichiNare'",
 "'Academy Productions'": "'Academy Productions'",
 "'Vega Entertainment'": "'Vega Entertainment'",
 "'Tsuburaya Productions'": "'Tsuburaya Productions'",
 "'Index'": "'Index'",
 "'Gigno Systems'": "'Gigno Systems'",
 "'Milky Cartoon'": "'Milky Cartoon'",
 "'G-mode'": "'G-mode'",
 "'SoftBank Creative Corp.'": "'SoftBank Creative Corp.'",
 "'T.O Entertainment'": "'T.O Entertainment'",
 "'Kokusai Eigasha'": "'Kokusai Eigasha'",
 "'Universal Pictures Japan'": "'Universal Pictures Japan'",
 "'Aubec'": "'Aubec'",
 "'North Stars Pictures'": "'North Stars Pictures'",
 "'5pb.'": "'5pb.'",
 "'Pencil'": "'Pencil'",
 "'Studio Mausu'": "'Studio Mausu'",
 "'GEN Productions'": "'GEN Productions'",
 "'Houbunsha'": "'Houbunsha'",
 "'NHK-BS2'": "'NHK-BS2'",
 "'Lucky Paradise'": "'Lucky Paradise'",
 "'Atlus'": "'Atlus'",
 "'Cyclone Graphics inc'": "'Cyclone Graphics inc'",
 "'SEDIC International'": "'SEDIC International'",
 "'Hakuhodo DY Music &amp; Pictures'": "'Hakuhodo DY Music &amp; Pictures'",
 "'Mainichi Shimbun'": "'Mainichi Shimbun'",
 "'Mushi Production'": "'Mushi Production'",
 "'Magic Bus'": "'Magic Bus'",
 "'Datam Polystar'": "'Datam Polystar'",
 "'Shogakukan Music &amp; Digital Entertainment'": "'Shogakukan Music &amp; Digital Entertainment'",
 "'Imagin'": "'Imagin'",
 "'Nihikime no Dozeu'": "'Nihikime no Dozeu'",
 "'Tokyo MX'": "'Tokyo MX'",
 "'Kyoraku Industrial Holdings'": "'Kyoraku Industrial Holdings'",
 "'Diomedea'": "'Diomedea'",
 "'Toranoana'": "'Toranoana'",
 "'Big Bang'": "'Big Bang'",
 "'Imagi'": "'Imagi'",
 "'AKOM'": "'AKOM'",
 "'Arcturus'": "'Arcturus'",
 "'Sanrio'": "'Sanrio'",
 "'Telescreen BV'": "'Telescreen BV'",
 "'Amuse'": "'Amuse'",
 "'Plum'": "'Plum'",
 "'Jinnan Studio'": "'Jinnan Studio'",
 "'NTT Docomo'": "'NTT Docomo'",
 "'Palm Studio'": "'Palm Studio'",
 "'Beat Frog'": "'Beat Frog'",
 "'Tokuma Japan'": "'Tokuma Japan'",
 "'Nexon'": "'Nexon'",
 "'Agent 21'": "'Agent 21'",
 "'Future Planet'": "'Future Planet'",
 "'Yahoo! Japan'": "'Yahoo! Japan'",
 "'Meiji Seika'": "'Meiji Seika'",
 "'Daiichikosho'": "'Daiichikosho'",
 "'Nikkatsu'": "'Nikkatsu'",
 "'Yellow Film'": "'Yellow Film'",
 "'Gainax'": "'Gainax'",
 "'Ministry of the Navy'": "'Ministry of the Navy'",
 "'MK Pictures'": "'MK Pictures'",
 "'Saban Entertainment'": "'Saban Entertainment'",
 "'Nintendo of America'": "'Nintendo of America'",
 "'Public &amp; Basic'": "'Public &amp; Basic'",
 "'JapanAnime'": "'JapanAnime'",
 "'Eye Move'": "'Eye Move'",
 "'Yumeta Company'": "'Yumeta Company'",
 "'Knack Productions'": "'Knack Productions'",
 "'Kino Production'": "'Kino Production'",
 "'Hiroshima Television'": "'Hiroshima Television'",
 "'Romantica club !!'": "'Romantica club !!'",
 "'Enoki Films'": "'Enoki Films'",
 "'Directions'": "'Directions'",
 "'Code'": "'Code'",
 "'Trick Block'": "'Trick Block'",
 "'ANIK'": "'ANIK'",
 "'Good Smile Company'": "'Good Smile Company'",
 "'PrimeTime'": "'PrimeTime'",
 "'Nitroplus'": "'Nitroplus'",
 "'4Kids Entertainment'": "'4Kids Entertainment'",
 "'Kinyosha'": "'Kinyosha'",
 "'Procidis'": "'Procidis'",
 "'D.A.S.T.'": "'D.A.S.T.'",
 "'501st JOINT FIGHTER WING'": "'501st JOINT FIGHTER WING'",
 "'PRA'": "'PRA'",
 "'Anime Antenna Iinkai'": "'Anime Antenna Iinkai'",
 "'Soyuzmultfilm'": "'Soyuzmultfilm'",
 "'Rankin/Bass'": "'Rankin/Bass'",
 "'White Bear'": "'White Bear'",
 "'Meruhensha'": "'Meruhensha'",
 "'Tele-Cartoon Japan'": "'Tele-Cartoon Japan'",
 "'Blue Eyes'": "'Blue Eyes'",
 "'MS Pictures'": "'MS Pictures'",
 "'Ichijinsha'": "'Ichijinsha'",
 "'Universal Studios'": "'Universal Studios'",
 "'Hoso Seisaku Doga'": "'Hoso Seisaku Doga'",
 "'Life Work'": "'Life Work'",
 "'AMG MUSIC'": "'AMG MUSIC'",
 "'Yoon&#039;s Color'": "'Yoon&#039;s Color'",
 "'Jam'": "'Jam'",
 "'Animac'": "'Animac'",
 "'Flex Comix'": "'Flex Comix'",
 "'Amino'": "'Amino'",
 "'T-Rex'": "'T-Rex'",
 "'Kadokawa Contents Gate'": "'Kadokawa Contents Gate'",
 "'Hobby Japan'": "'Hobby Japan'",
 "'Kaeruotoko Shokai'": "'Kaeruotoko Shokai'",
 "'feng'": "'feng'",
 "'Minami Machi Bugyousho'": "'Minami Machi Bugyousho'",
 "'Studio Kikan'": "'Studio Kikan'",
 "'Walt Disney Studios'": "'Walt Disney Studios'",
 "'Studio Moriken'": "'Studio Moriken'",
 "'Daume'": "'Daume'",
 "'Robot Communications'": "'Robot Communications'",
 "'Kiyosumi High School Mahjong Club'": "'Kiyosumi High School Mahjong Club'",
 "'Gentosha Comics'": "'Gentosha Comics'",
 "'Walkers Company'": "'Walkers Company'",
 "'Earth Star Entertainment'": "'Earth Star Entertainment'",
 "'Mobcast'": "'Mobcast'",
 "'Nihon Eizo'": "'Nihon Eizo'",
 "'Ryukyu Asahi Broadcasting'": "'Ryukyu Asahi Broadcasting'",
 "'International Digital Artist'": "'International Digital Artist'",
 "'Cospa'": "'Cospa'",
 "'Primastea'": "'Primastea'",
 "'Enterbrain'": "'Enterbrain'",
 "'Innocent Grey'": "'Innocent Grey'",
 "'Raku High Student Council'": "'Raku High Student Council'",
 "'Cotton Doll'": "'Cotton Doll'",
 "'Warner Bros.'": "'Warner Bros.'",
 "'Bungeishunjuu'": "'Bungeishunjuu'",
 "'Takara'": "'Takara'",
 "'Casio Entertainment'": "'Casio Entertainment'",
 "'Hisashishi Videos'": "'Hisashishi Videos'",
 "'TOMY Company'": "'TOMY Company'",
 "'CREi'": "'CREi'",
 "'Usagi Ou'": "'Usagi Ou'",
 "'Xebec'": "'Xebec'",
 "'Zyc'": "'Zyc'",
 "'Studio Pastoral'": "'Studio Pastoral'",
 "'BIGLOBE'": "'BIGLOBE'",
 "'JM Animation'": "'JM Animation'",
 "'Aoni Entertainment'": "'Aoni Entertainment'",
 "'RAY'": "'RAY'",
 "'BS11'": "'BS11'",
 "'Liverpool'": "'Liverpool'",
 "'Shinano Kikaku'": "'Shinano Kikaku'",
 "'Chrono Gear Creative'": "'Chrono Gear Creative'",
 "'AG-ONE'": "'AG-ONE'",
 "'OLE-M'": "'OLE-M'",
 "'KMMJ Studios'": "'KMMJ Studios'",
 "'Purple Cow Studio Japan'": "'Purple Cow Studio Japan'",
 "'Kinoshita Koumuten'": "'Kinoshita Koumuten'",
 "'Fields'": "'Fields'",
 "'Visual 80'": "'Visual 80'",
 "'Hoods Entertainment'": "'Hoods Entertainment'",
 "'Jumondo'": "'Jumondo'",
 "'Valkyria'": "'Valkyria'",
 "'Infinite'": "'Infinite'",
 "'Studio G-1Neo'": "'Studio G-1Neo'",
 "'Studio Pierrot'": "'Studio Pierrot'",
 "'Jinnis Animation Studios'": "'Jinnis Animation Studios'",
 "'Madoka Partners'": "'Madoka Partners'",
 "'Warner Music Japan'": "'Warner Music Japan'",
 "'Studio Gram'": "'Studio Gram'",
 "'Dream Creation'": "'Dream Creation'",
 "'Dentsu Razorfish'": "'Dentsu Razorfish'",
 "'SUBARU'": "'SUBARU'",
 "'Sony Music Communications'": "'Sony Music Communications'",
 "'Seikaisha'": "'Seikaisha'",
 "'I was a Ballerina'": "'I was a Ballerina'",
 "'The Answer Studio'": "'The Answer Studio'",
 "'Enlight Pictures'": "'Enlight Pictures'",
 "'Studio Mir'": "'Studio Mir'",
 "'Bulls Eye'": "'Bulls Eye'",
 "'Indeprox'": "'Indeprox'",
 "'Kimi To Boku Production Partners'": "'Kimi To Boku Production Partners'",
 "'ING'": "'ING'",
 "'The Berich'": "'The Berich'",
 "'Konami Digital Entertainment'": "'Konami Digital Entertainment'",
 "'Pixy'": "'Pixy'",
 "'M.S.C'": "'M.S.C'",
 "'Glovision'": "'Glovision'",
 "'12 Diary Holders'": "'12 Diary Holders'",
 "'Project IS'": "'Project IS'",
 "'Slowcurve'": "'Slowcurve'",
 "'indigo line'": "'indigo line'",
 "'OLM'": "'OLM'",
 "'Cammot'": "'Cammot'",
 "'Inu x Boku SS Production Partners'": "'Inu x Boku SS Production Partners'",
 "'Grooove'": "'Grooove'",
 "'Ultra Super Pictures'": "'Ultra Super Pictures'",
 "'MAGES.'": "'MAGES.'",
 "'Fujimi Shobo'": "'Fujimi Shobo'",
 "'Gakken Eigakyoku'": "'Gakken Eigakyoku'",
 "'Ishimori Pro'": "'Ishimori Pro'",
 "'Hakoniwa Academy Student Council'": "'Hakoniwa Academy Student Council'",
 "'Hot Bear'": "'Hot Bear'",
 "'Mary Jane'": "'Mary Jane'",
 "'Right Gauge'": "'Right Gauge'",
 "'Dwango Music Entertainment'": "'Dwango Music Entertainment'",
 "'StudioRF Inc.'": "'StudioRF Inc.'",
 "'Saban Brands'": "'Saban Brands'",
 "'BS-TBS'": "'BS-TBS'",
 "'Volks'": "'Volks'",
 "'Jormungand Production Partners'": "'Jormungand Production Partners'",
 "'Tasogare Otome×Amnesia Production Partners'": "'Tasogare Otome×Amnesia Production Partners'",
 "'Project Eureka AO'": "'Project Eureka AO'",
 "'Sammy'": "'Sammy'",
 "'Planet'": "'Planet'",
 "'LandQ studios'": "'LandQ studios'",
 "'Viki'": "'Viki'",
 "'tsuritama partners'": "'tsuritama partners'",
 "'Myung Films'": "'Myung Films'",
 "'Furyu'": "'Furyu'",
 "'Queen Bee'": "'Queen Bee'",
 "'Fanworks'": "'Fanworks'",
 "'Aniplex of America'": "'Aniplex of America'",
 "'Po10tial'": "'Po10tial'",
 "'Asahi Shimbun'": "'Asahi Shimbun'",
 "'Visual Vision'": "'Visual Vision'",
 "'Rironsha'": "'Rironsha'",
 "'Media Do'": "'Media Do'",
 "'Studio elle'": "'Studio elle'",
 "'BS NTV'": "'BS NTV'",
 "'TOHO animation'": "'TOHO animation'",
 "'Rabbit Gate'": "'Rabbit Gate'",
 "'Q-Tec'": "'Q-Tec'",
 "'Tokyo Theatres'": "'Tokyo Theatres'",
 "'Toppan Printing'": "'Toppan Printing'",
 "'Keisei Electric Railway'": "'Keisei Electric Railway'",
 "'Gree'": "'Gree'",
 "'Pastel'": "'Pastel'",
 "'AIR AGENCY'": "'AIR AGENCY'",
 "'Animatsu Entertainment'": "'Animatsu Entertainment'",
 "'Project No Name'": "'Project No Name'",
 "'Miracle Bus'": "'Miracle Bus'",
 "'BS Fuji'": "'BS Fuji'",
 "'Exit Tunes'": "'Exit Tunes'",
 "'UNLIMITED Partners'": "'UNLIMITED Partners'",
 "'i0+'": "'i0+'",
 "'Studio Blanc'": "'Studio Blanc'",
 "'SPO Entertainment'": "'SPO Entertainment'",
 "'Kenji Studio'": "'Kenji Studio'",
 "'Solid Vox'": "'Solid Vox'",
 "'Bouncy'": "'Bouncy'",
 "'Kinoshita Group Holdings'": "'Kinoshita Group Holdings'",
 "'NOTTV'": "'NOTTV'",
 "'Mad Box'": "'Mad Box'",
 "'Shingeki no Kyojin Team'": "'Shingeki no Kyojin Team'",
 "'Daiichi Shokai CO.": "'Daiichi Shokai CO.",
 "LTD'": "LTD'",
 "'KBS'": "'KBS'",
 "'Tsubasa Entertainment'": "'Tsubasa Entertainment'",
 "'Just Pro'": "'Just Pro'",
 "'Nomad'": "'Nomad'",
 "'Bushiroad Music'": "'Bushiroad Music'",
 "'Marza Animation Planet'": "'Marza Animation Planet'",
 "'Senran Kagura Partners'": "'Senran Kagura Partners'",
 "'Studio Zealot'": "'Studio Zealot'",
 "'Avex Pictures'": "'Avex Pictures'",
 "'Lune Pictures'": "'Lune Pictures'",
 "'Angelfish'": "'Angelfish'",
 "'Digital Media Lab'": "'Digital Media Lab'",
 "'ACC Production'": "'ACC Production'",
 "'ZERO-A'": "'ZERO-A'",
 "'Tokai Television'": "'Tokai Television'",
 "'Felix Film'": "'Felix Film'",
 "'Brave Hearts'": "'Brave Hearts'",
 "'DLE'": "'DLE'",
 "'Xing'": "'Xing'",
 "'Lawson HMV Entertainment'": "'Lawson HMV Entertainment'",
 "'Opera House'": "'Opera House'",
 "'GYAO!'": "'GYAO!'",
 "'Overlap'": "'Overlap'",
 "'Iwatobi High School Swimming Club'": "'Iwatobi High School Swimming Club'",
 "'Graphinica'": "'Graphinica'",
 "'Docomo Anime Store'": "'Docomo Anime Store'",
 "'Lucent Pictures Entertainment'": "'Lucent Pictures Entertainment'",
 "'DIVE II Entertainment'": "'DIVE II Entertainment'",
 "'3xCube'": "'3xCube'",
 "'Baramiri'": "'Baramiri'",
 "'DeNA'": "'DeNA'",
 "'Wit Studio'": "'Wit Studio'",
 "'Pashmina'": "'Pashmina'",
 "'Orange'": "'Orange'",
 "'JP Room'": "'JP Room'",
 "'Otogi Production'": "'Otogi Production'",
 "'Wako Productions'": "'Wako Productions'",
 "'Ai Addiction'": "'Ai Addiction'",
 "'A-Sketch'": "'A-Sketch'",
 "'Kadokawa Media House'": "'Kadokawa Media House'",
 "'ZIZ Entertainment (ZIZ)'": "'ZIZ Entertainment (ZIZ)'",
 "'EXA International'": "'EXA International'",
 "'Sentai Filmworks'": "'Sentai Filmworks'",
 "'Studio CHANT'": "'Studio CHANT'",
 "'Tsukuru no Mori'": "'Tsukuru no Mori'",
 "'I Will'": "'I Will'",
 "'Bandai Namco Live Creative'": "'Bandai Namco Live Creative'",
 "'Steve N&#039; Steven'": "'Steve N&#039; Steven'",
 "'1st PLACE'": "'1st PLACE'",
 "'Cygames'": "'Cygames'",
 "'Animatic'": "'Animatic'",
 "'TC Entertainment'": "'TC Entertainment'",
 "'Forecast Communications'": "'Forecast Communications'",
 "'HeART-BIT'": "'HeART-BIT'",
 "'Hokkaido Azmacy'": "'Hokkaido Azmacy'",
 "'Hokkaido Cultural Broadcasting'": "'Hokkaido Cultural Broadcasting'",
 "'C2C'": "'C2C'",
 "'Voyager Entertainment'": "'Voyager Entertainment'",
 "'Twin Engine'": "'Twin Engine'",
 "'NAZ'": "'NAZ'",
 "'Toy&#039;s Factory'": "'Toy&#039;s Factory'",
 "'Anime Consortium Japan'": "'Anime Consortium Japan'",
 "'famima.com'": "'famima.com'",
 "'QREAZY'": "'QREAZY'",
 "'DandeLion Animation Studio LLC'": "'DandeLion Animation Studio LLC'",
 "'Trans Cosmos'": "'Trans Cosmos'",
 "'Production GoodBook'": "'Production GoodBook'",
 "'Comic Umenohone'": "'Comic Umenohone'",
 "'BIGFACE'": "'BIGFACE'",
 "'Age Global Networks'": "'Age Global Networks'",
 "'ILCA'": "'ILCA'",
 "'Top-Insight International Co.": "'Top-Insight International Co.",
 "LTD.'": "LTD.'",
 "'Contents Seed'": "'Contents Seed'",
 "'White Fox'": "'White Fox'",
 "'Evil Line Records'": "'Evil Line Records'",
 "'Craftar'": "'Craftar'",
 "'Sankyo Planning'": "'Sankyo Planning'",
 "'Studio GOONEYS'": "'Studio GOONEYS'",
 "'Harappa'": "'Harappa'",
 "'Techno Sound'": "'Techno Sound'",
 "'Mirai Film'": "'Mirai Film'",
 "'bilibili'": "'bilibili'",
 "'Kanon Sound'": "'Kanon Sound'",
 "'Hobibox'": "'Hobibox'",
 "'Yaoqi'": "'Yaoqi'",
 "'Sound Team Don Juan'": "'Sound Team Don Juan'",
 "'Pazzy Entertainment'": "'Pazzy Entertainment'",
 "'Hiroshi Planning'": "'Hiroshi Planning'",
 "'ABC Animation'": "'ABC Animation'",
 "'Quaras'": "'Quaras'",
 "'Fujishouji'": "'Fujishouji'",
 "'Tencent Animation'": "'Tencent Animation'",
 "'Studio LAN'": "'Studio LAN'",
 "'iQIYI'": "'iQIYI'",
 "'comico'": "'comico'",
 "'Shirogumi'": "'Shirogumi'",
 "'BS Japan'": "'BS Japan'",
 "'Kadokawa'": "'Kadokawa'",
 "'Tokuma Japan Communications'": "'Tokuma Japan Communications'",
 "'Diabolik Lovers MB Project'": "'Diabolik Lovers MB Project'",
 "'Lawson'": "'Lawson'",
 "'C &amp; I entertainment'": "'C &amp; I entertainment'",
 "'Nelke Planning'": "'Nelke Planning'",
 "'East Japan Marketing &amp; Communications'": "'East Japan Marketing &amp; Communications'",
 "'Shizuoka Broadcasting System'": "'Shizuoka Broadcasting System'",
 "'Assez Finaud Fabric'": "'Assez Finaud Fabric'",
 "'Trigger'": "'Trigger'",
 "'Being'": "'Being'",
 "'eBooK Initiative Japan CO.": "'eBooK Initiative Japan CO.",
 "'ensky'": "'ensky'",
 "'Bandai Namco Pictures'": "'Bandai Namco Pictures'",
 "'Fujio Production'": "'Fujio Production'",
 "'Fujiko F. Fujio Pro'": "'Fujiko F. Fujio Pro'",
 "'Yomiuri TV Enterprise'": "'Yomiuri TV Enterprise'",
 "'Adores'": "'Adores'",
 "'Heroz'": "'Heroz'",
 "'Penta Show Studios'": "'Penta Show Studios'",
 "'Colored-Pencil Animation Design'": "'Colored-Pencil Animation Design'",
 "'Milestone Music Publishing'": "'Milestone Music Publishing'",
 "'Music Ray&#039;n'": "'Music Ray&#039;n'",
 "'RAB Aomori Broadcasting'": "'RAB Aomori Broadcasting'",
 "'Nippon Television Music'": "'Nippon Television Music'",
 "'Medicos Entertainment'": "'Medicos Entertainment'",
 "'Radio Osaka'": "'Radio Osaka'",
 "'Duckbill Entertainment'": "'Duckbill Entertainment'",
 "'Shanghai Tiantan Culture &amp; Media'": "'Shanghai Tiantan Culture &amp; Media'",
 "'NADA Holdings'": "'NADA Holdings'",
 "'My Theater D.D.'": "'My Theater D.D.'",
 "'Crunchyroll SC Anime Fund'": "'Crunchyroll SC Anime Fund'",
 "'Hobi Animation'": "'Hobi Animation'",
 "'TEAM Entertainment Inc.'": "'TEAM Entertainment Inc.'",
 "'Chugai Mining Co.": "'Chugai Mining Co.",
 "Ltd.'": "Ltd.'",
 "'Epicross'": "'Epicross'",
 "'Cromea'": "'Cromea'",
 "'F.M.F'": "'F.M.F'",
 "'Telecom Animation Film'": "'Telecom Animation Film'",
 "'U-NEXT'": "'U-NEXT'",
 "'Plus One'": "'Plus One'",
 "'Chippai'": "'Chippai'",
 "'Virgin Babylon Records'": "'Virgin Babylon Records'",
 "'Tencent Penguin Pictures'": "'Tencent Penguin Pictures'",
 "'China Literature Limited'": "'China Literature Limited'",
 "'Sun TV'": "'Sun TV'",
 "'TV Saitama'": "'TV Saitama'",
 "'Chiba TV'": "'Chiba TV'",
 "'EDGE'": "'EDGE'",
 "'Fuji&amp;gumi Games'": "'Fuji&amp;gumi Games'",
 "'BOOTLEG'": "'BOOTLEG'",
 "'Kadokawa Media (Taiwan)'": "'Kadokawa Media (Taiwan)'",
 "'Tose'": "'Tose'",
 "'Yuhodo'": "'Yuhodo'",
 "'Haoliners Animation League'": "'Haoliners Animation League'",
 "'DMM pictures'": "'DMM pictures'",
 "'Greenwood'": "'Greenwood'",
 "'Japan Sleeve'": "'Japan Sleeve'",
 "'LIDENFILMS'": "'LIDENFILMS'",
 "'Koei Tecmo Games'": "'Koei Tecmo Games'",
 "'Azumaker'": "'Azumaker'",
 "'Children&#039;s Playground Entertainment'": "'Children&#039;s Playground Entertainment'",
 "'Level-5'": "'Level-5'",
 "'Zack Promotion'": "'Zack Promotion'",
 "'Takara Tomy A.R.T.S'": "'Takara Tomy A.R.T.S'",
 "'CyberAgent'": "'CyberAgent'",
 "'Nishinippon Broadcasting'": "'Nishinippon Broadcasting'",
 "'Dai Nippon Printing'": "'Dai Nippon Printing'",
 "'Shinchosha'": "'Shinchosha'",
 "'project lights'": "'project lights'",
 "'Audio Planning U'": "'Audio Planning U'",
 "'Shin-Ei Animation'": "'Shin-Ei Animation'",
 "'Sumitomo'": "'Sumitomo'",
 "'Lastrum Music'": "'Lastrum Music'",
 "'Sanyo Bussan'": "'Sanyo Bussan'",
 "'Tencent Japan'": "'Tencent Japan'",
 "'Bishop'": "'Bishop'",
 "'Emon'": "'Emon'",
 "'MMDGP'": "'MMDGP'",
 "'Kobunsha'": "'Kobunsha'",
 "'Kanetsu Co.": "'Kanetsu Co.",
 "'CIC'": "'CIC'",
 "'Shochiku Music Publishing'": "'Shochiku Music Publishing'",
 "'Highlights Entertainment'": "'Highlights Entertainment'",
 "'Links'": "'Links'",
 "'DMM.com'": "'DMM.com'",
 "'Digital Frontier'": "'Digital Frontier'",
 "'Hulu'": "'Hulu'",
 "'Sapporo Television Broadcasting'": "'Sapporo Television Broadcasting'",
 "'Miyagi Television Broadcasting'": "'Miyagi Television Broadcasting'",
 "'Shizuoka Daiichi Television'": "'Shizuoka Daiichi Television'",
 "'Chukyo TV Broadcasting'": "'Chukyo TV Broadcasting'",
 "'Fukuoka Broadcasting System'": "'Fukuoka Broadcasting System'",
 "'Pierrot Plus'": "'Pierrot Plus'",
 "'Bandai Namco Rights Marketing'": "'Bandai Namco Rights Marketing'",
 "'RightTracks'": "'RightTracks'",
 "'Amgakuin'": "'Amgakuin'",
 "'COLOPL'": "'COLOPL'",
 "'KDDI'": "'KDDI'",
 "'Dear Stage inc.'": "'Dear Stage inc.'",
 "'Chukong Technologies'": "'Chukong Technologies'",
 "'Sunrise Music Publishing'": "'Sunrise Music Publishing'",
 "'NHK Enterprises'": "'NHK Enterprises'",
 "'Smiral Animation'": "'Smiral Animation'",
 "'Wargaming Japan'": "'Wargaming Japan'",
 "'JTB Entertainment'": "'JTB Entertainment'",
 "'Studio NOIX'": "'Studio NOIX'",
 "'Gen&#039;ei'": "'Gen&#039;ei'",
 "'Egg Firm'": "'Egg Firm'",
 "'Production Ace'": "'Production Ace'",
 "'Quick Corporation'": "'Quick Corporation'",
 "'XFLAG'": "'XFLAG'",
 "'XFLAG Pictures'": "'XFLAG Pictures'",
 "'NTT Plala'": "'NTT Plala'",
 "'World Cosplay Summit'": "'World Cosplay Summit'",
 "'Orchid Seed'": "'Orchid Seed'",
 "'Stardust Promotion'": "'Stardust Promotion'",
 "'PansonWorks'": "'PansonWorks'",
 "'Jidaigeki Channel'": "'Jidaigeki Channel'",
 "'Shufunotomo'": "'Shufunotomo'",
 "'Hakuhodo'": "'Hakuhodo'",
 "'Kakao Japan'": "'Kakao Japan'",
 "'Coamix'": "'Coamix'",
 "'Parco'": "'Parco'",
 "'e-notion'": "'e-notion'",
 "'Quatre Stella'": "'Quatre Stella'",
 "'Kadokawa Daiei Studio'": "'Kadokawa Daiei Studio'",
 "'Kotobukiya'": "'Kotobukiya'",
 "'China Animation Characters'": "'China Animation Characters'",
 "'NHN PlayArt'": "'NHN PlayArt'",
 "'Ima Group'": "'Ima Group'",
 "'AZ Creative'": "'AZ Creative'",
 "'KLab'": "'KLab'",
 "'LINE Corporation'": "'LINE Corporation'",
 "'Rakuten'": "'Rakuten'",
 "'Top Marshal'": "'Top Marshal'",
 "'Khara'": "'Khara'",
 "'Walt Disney Japan'": "'Walt Disney Japan'",
 "'KEN ON'": "'KEN ON'",
 "'D.N.dreampartners'": "'D.N.dreampartners'",
 "'Yomiuri Shimbun'": "'Yomiuri Shimbun'",
 "'Drecom'": "'Drecom'",
 "'Pb Animation Co. Ltd.'": "'Pb Animation Co. Ltd.'",
 "'Asgard'": "'Asgard'",
 "'Kujou-kun no Bonnou wo Mimamoru-kai'": "'Kujou-kun no Bonnou wo Mimamoru-kai'",
 "'Marui Group'": "'Marui Group'",
 "'DJI'": "'DJI'",
 "'Donuts'": "'Donuts'",
 "'Kyotoma'": "'Kyotoma'",
 "'Tate Anime'": "'Tate Anime'",
 "'Melonbooks'": "'Melonbooks'",
 "'JY Animation'": "'JY Animation'",
 "'Live Viewing Japan'": "'Live Viewing Japan'",
 "'Neft Film'": "'Neft Film'",
 "'W-Toon Studio'": "'W-Toon Studio'",
 "'DMM.futureworks'": "'DMM.futureworks'",
 "'Gzbrain'": "'Gzbrain'",
 "'Cocoro Free'": "'Cocoro Free'",
 "'Tosho Printing'": "'Tosho Printing'",
 "'Studio Hibari'": "'Studio Hibari'",
 "'AKABEiSOFT2'": "'AKABEiSOFT2'",
 "'Moonbell'": "'Moonbell'",
 "'INCS toenter'": "'INCS toenter'",
 "'ONEMUSIC'": "'ONEMUSIC'",
 "'NewGin'": "'NewGin'",
 "'Aquamarine'": "'Aquamarine'",
 "'Universal Entertainment'": "'Universal Entertainment'",
 "'D-techno'": "'D-techno'",
 "'CLOVERWORKS'": "'CLOVERWORKS'",
 "'Spacey Music Entertainment'": "'Spacey Music Entertainment'",
 "'A-Craft'": "'A-Craft'",
 "'Tohan Corporation'": "'Tohan Corporation'",
 "'Yamasa'": "'Yamasa'",
 "'Hipland Music Corporation'": "'Hipland Music Corporation'",
 "'Muse Communication Co.": "'Muse Communication Co.",
 "'Medicrie'": "'Medicrie'",
 "'Yoshimoto Creative Agency'": "'Yoshimoto Creative Agency'",
 "'Shanghai Jump Network Technology'": "'Shanghai Jump Network Technology'",
 "'Kawade Shobo Shinsha'": "'Kawade Shobo Shinsha'",
 "'Studio A-CAT'": "'Studio A-CAT'",
 "'D &amp; D Pictures'": "'D &amp; D Pictures'",
 "'Benesse Corporation'": "'Benesse Corporation'",
 "'Ki/oon Music'": "'Ki/oon Music'",
 "'Picante Circus'": "'Picante Circus'",
 "'Suiseisha'": "'Suiseisha'",
 "'Tavac'": "'Tavac'",
 "'Frencel'": "'Frencel'",
 "'Jay Zone Comic'": "'Jay Zone Comic'",
 "'Warner Bros. Japan'": "'Warner Bros. Japan'"}