version: "3.9.5"

services:
  backend:
    build:
      context: ./backend
      dockerfile: dockerfile
    ports:
      - "5000:5000"
    volumes:
      - C:/Users/Arthy/Desktop/Project_MLOPS/backend:/app/backend

  frontend:
    build:
      context: .
      dockerfile: dockerfile
    ports:
      - "4000:4000"
    volumes:
      - C:/Users/Arthy/Desktop/Project_MLOPS:/app/frontend

  prometheus: 
    image: prom/prometheus:latest 
    container_name: prometheus 
    restart: unless-stopped 
    volumes: 
      - C:/Users/Arthy/Desktop/Project_MLOPS/promotheus_data:/prometheus
    command:
      - '--config.file=/etc/prometheus/prometheus.yml'
      - '--storage.tsdb.path=/prometheus'
      - '--web.console.libraries=/etc/prometheus/console_libraries'
      - '--web.console.templates=/etc/prometheus/consoles'
      - '--web.enable-lifecycle'
    ports: 
      - 9090:9090

  grafana:
    image: grafana/grafana
    ports:
      - "3000:3000"
    environment:
      GF_INSTALL_PLUGINS: grafana-piechart-panel
    volumes:
      - ./grafana/provisioning:/etc/grafana/provisioning

